// Copyright (c) 2026, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
package com.oracle.database.spring.testcontainers;

import java.io.IOException;
import java.nio.file.DirectoryNotEmptyException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;
import java.util.regex.Matcher;

import com.github.dockerjava.api.command.InspectContainerResponse;
import com.github.dockerjava.api.model.Capability;
import com.github.dockerjava.api.model.Device;
import com.github.dockerjava.api.model.HostConfig;
import org.testcontainers.containers.Container;
import org.testcontainers.containers.ContainerLaunchException;
import org.testcontainers.containers.ExecConfig;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.images.builder.Transferable;
import org.testcontainers.utility.DockerImageName;

/**
 * Testcontainers implementation for the official Oracle Autonomous AI Database Free image.
 *
 * <p>The container starts an Autonomous Transaction Processing (ATP) database by default.
 * It configures the image's required {@code SYS_ADMIN} capability and {@code /dev/fuse}
 * device access.</p>
 *
 * <p>Clients connect with the TLS wallet generated by the image. The wallet is available
 * at {@value #TLS_WALLET_PATH}; this class deliberately does not extend
 * {@code JdbcDatabaseContainer}, because configuring a JDBC client requires that wallet
 * and trust material.</p>
 *
 * <p>Supported image: {@code container-registry.oracle.com/database/adb-free}</p>
 */
public class ADBContainer extends GenericContainer<ADBContainer> {

    /** Official Oracle Autonomous AI Database Free container image. */
    public static final String IMAGE_NAME = "container-registry.oracle.com/database/adb-free";
    /** Default image tag for the current multi-architecture image. */
    public static final String DEFAULT_TAG = "latest-26ai";
    /** TLS database listener port inside the container. */
    public static final int TLS_PORT = 1521;
    /** Mutual TLS database listener port inside the container. */
    public static final int MTLS_PORT = 1522;
    /** Oracle REST Data Services HTTPS port. */
    public static final int HTTPS_PORT = 8443;
    /** MongoDB API port. */
    public static final int MONGODB_API_PORT = 27017;
    /** Location of the TLS wallet generated at container startup. */
    public static final String TLS_WALLET_PATH = "/u01/app/oracle/wallets/tls_wallet";

    private static final DockerImageName DEFAULT_IMAGE = DockerImageName.parse(IMAGE_NAME);
    private static final String ADMIN_PASSWORD_ENV = "ADMIN_PASSWORD";
    private static final String WALLET_PASSWORD_ENV = "WALLET_PASSWORD";
    private static final String WORKLOAD_TYPE_ENV = "WORKLOAD_TYPE";
    private static final String DATABASE_NAME_ENV = "DATABASE_NAME";
    private static final String ENABLE_ARCHIVE_LOG_ENV = "ENABLE_ARCHIVE_LOG";
    private static final String FUSE_DEVICE = "/dev/fuse";
    private static final String ORACLE_ADMIN_USERNAME = "ADMIN";
    private static final String ORACLE_IDENTIFIER_PATTERN = "[A-Z][A-Z0-9_$#]{0,127}";
    private static final String APP_USER_SCRIPT_PREFIX = "/tmp/adb-free-app-user-";
    private static final int OWNER_READ_WRITE_FILE_MODE = 0600;
    private static final String ROOT_USER = "0";
    private static final Duration DEFAULT_STARTUP_TIMEOUT = Duration.ofMinutes(20);
    private static final List<String> WALLET_FILES = List.of(
            "adb_container.cert", "cwallet.sso", "ewallet.p12", "keystore.jks", "truststore.jks",
            "ojdbc.properties", "sqlnet.ora", "tnsnames.ora");

    private WorkloadType workloadType = WorkloadType.ATP;
    private String databaseName;
    private AppUserConfiguration appUser;
    private List<String> appUserRoles = List.of();

    /** Supported Autonomous AI Database Free workload types. */
    public enum WorkloadType {
        /** Autonomous Transaction Processing workload. */
        ATP,
        /** Autonomous AI Database Lakehouse workload. */
        ADW
    }

    /** Creates a container using the official image and default tag. */
    public ADBContainer() {
        this(IMAGE_NAME + ":" + DEFAULT_TAG);
    }

    /**
     * Creates a container using an image name.
     *
     * @param dockerImageName compatible Oracle Autonomous AI Database Free image name
     */
    public ADBContainer(String dockerImageName) {
        this(DockerImageName.parse(dockerImageName));
    }

    /**
     * Creates a container using a parsed image name.
     *
     * @param dockerImageName compatible Oracle Autonomous AI Database Free image name
     */
    public ADBContainer(DockerImageName dockerImageName) {
        super(dockerImageName);
        dockerImageName.assertCompatibleWith(DEFAULT_IMAGE);
        this.withExposedPorts(TLS_PORT, MTLS_PORT, HTTPS_PORT, MONGODB_API_PORT)
                .waitingFor(Wait.forListeningPort().withStartupTimeout(DEFAULT_STARTUP_TIMEOUT))
                .withCreateContainerCmdModifier(
                        command -> {
                            HostConfig hostConfig = command.getHostConfig();
                            if (hostConfig == null) {
                                hostConfig = HostConfig.newHostConfig();
                                command.withHostConfig(hostConfig);
                            }
                            configureRequiredRuntime(hostConfig);
                        });
    }

    /**
     * Configures the Autonomous Database workload started by the image.
     *
     * @param workloadType ATP or ADW
     * @return this container
     */
    public ADBContainer withWorkloadType(WorkloadType workloadType) {
        if (workloadType == null) {
            throw new IllegalArgumentException("Workload type cannot be null");
        }
        this.workloadType = workloadType;
        return self();
    }

    /**
     * Configures the name of the initial Autonomous AI Database.
     *
     * <p>When unset, the image creates {@code MYATP} or {@code MYADW}, based on
     * the selected workload type.</p>
     *
     * @param databaseName alphanumeric database name
     * @return this container
     */
    public ADBContainer withDatabaseName(String databaseName) {
        String normalizedDatabaseName = requireNonBlank(databaseName, "Database name").toUpperCase(Locale.ROOT);
        if (!normalizedDatabaseName.matches("[A-Z0-9]+")) {
            throw new IllegalArgumentException("Database name must contain only alphanumeric characters");
        }
        this.databaseName = normalizedDatabaseName;
        return self();
    }

    /**
     * Configures the mandatory database administrator password.
     *
     * @param adminPassword administrator password for the initial Autonomous Database
     * @return this container
     */
    public ADBContainer withAdminPassword(String adminPassword) {
        requireValidAdminPassword(adminPassword);
        return withEnv(ADMIN_PASSWORD_ENV, adminPassword);
    }

    /**
     * Configures the mandatory password used to generate the client TLS wallet.
     *
     * @param walletPassword TLS wallet password
     * @return this container
     */
    public ADBContainer withWalletPassword(String walletPassword) {
        requireValidWalletPassword(walletPassword);
        return withEnv(WALLET_PASSWORD_ENV, walletPassword);
    }

    /**
     * Enables or disables archive logging in the initial Autonomous AI Database.
     *
     * @param enabled whether archive logging is enabled
     * @return this container
     */
    public ADBContainer withArchiveLog(boolean enabled) {
        return withEnv(ENABLE_ARCHIVE_LOG_ENV, Boolean.toString(enabled));
    }

    /**
     * Configures an optional application user to create after the database is ready.
     * The user always receives {@code CREATE SESSION}; add database roles with
     * {@link #withAppUserRoles(String...)}.
     *
     * @param username application user name
     * @param password application user password
     * @return this container
     */
    public ADBContainer withAppUser(String username, String password) {
        String normalizedUsername = requireAppUserUsername(username);
        requireValidSqlPassword(password, "Application user password");
        this.appUser = new AppUserConfiguration(normalizedUsername, password);
        return self();
    }

    /**
     * Replaces the roles granted to the configured application user.
     *
     * @param roles application-user roles
     * @return this container
     */
    public ADBContainer withAppUserRoles(String... roles) {
        if (roles == null) {
            throw new IllegalArgumentException("Application user roles cannot be null");
        }

        List<String> normalizedRoles = new ArrayList<>();
        for (String role : roles) {
            String normalizedRole = requireUnquotedIdentifier(role, "Application user role");
            if (!normalizedRoles.contains(normalizedRole)) {
                normalizedRoles.add(normalizedRole);
            }
        }
        appUserRoles = List.copyOf(normalizedRoles);
        return self();
    }

    /**
     * Returns the initial Autonomous AI Database name.
     *
     * @return configured database name, or the workload-specific image default
     */
    public String getDatabaseName() {
        return databaseName == null ? "MY" + workloadType.name() : databaseName;
    }

    /**
     * Returns the mapped TLS database listener port.
     *
     * @return mapped TLS port
     */
    public Integer getTlsPort() {
        return getMappedPort(TLS_PORT);
    }

    /**
     * Returns the mapped mutual TLS database listener port.
     *
     * @return mapped mutual TLS port
     */
    public Integer getMtlsPort() {
        return getMappedPort(MTLS_PORT);
    }

    /**
     * Returns the mapped Oracle REST Data Services HTTPS port.
     *
     * @return mapped HTTPS port
     */
    public Integer getHttpsPort() {
        return getMappedPort(HTTPS_PORT);
    }

    /**
     * Returns the mapped MongoDB API port.
     *
     * @return mapped MongoDB API port
     */
    public Integer getMongoDbApiPort() {
        return getMappedPort(MONGODB_API_PORT);
    }

    /**
     * Returns the medium-service mutual TLS alias for the initial database.
     *
     * @return mutual TLS service alias
     */
    public String getMtlsServiceAlias() {
        return getDatabaseName().toLowerCase(Locale.ROOT) + "_medium";
    }

    /**
     * Returns the medium-service TLS alias for the initial database.
     *
     * @return TLS service alias
     */
    public String getTlsServiceAlias() {
        return getMtlsServiceAlias() + "_tls";
    }

    /**
     * Copies the generated client wallet to a local directory and updates its
     * {@code tnsnames.ora} entries for this container's mapped host ports.
     *
     * <p>Call this after the container has started. Configure JDBC with the
     * returned directory as {@code oracle.net.tns_admin}, then use
     * {@link #getMtlsServiceAlias()} or {@link #getTlsServiceAlias()}.</p>
     *
     * @param destination local directory that receives the wallet files
     * @return an auto-closeable wallet handle for the destination directory
     * @throws IOException if wallet files cannot be written
     */
    public Wallet copyWalletTo(Path destination) throws IOException {
        if (destination == null) {
            throw new IllegalArgumentException("Wallet destination cannot be null");
        }
        Files.createDirectories(destination);
        try {
            for (String fileName : WALLET_FILES) {
                copyFileFromContainer(TLS_WALLET_PATH + "/" + fileName, destination.resolve(fileName).toString());
            }
            updateWalletNetworkAddresses(destination.resolve("tnsnames.ora"));
            return new Wallet(destination);
        } catch (IOException | RuntimeException exception) {
            try {
                new Wallet(destination).close();
            } catch (IOException cleanupException) {
                exception.addSuppressed(cleanupException);
            }
            throw exception;
        }
    }

    @Override
    protected void containerIsStarted(InspectContainerResponse containerInfo) {
        super.containerIsStarted(containerInfo);
        if (appUser != null) {
            provisionAppUser(appUser);
        }
    }

    /**
     * Handle for wallet files copied from an ADB Free container.
     *
     * <p>Closing the handle deletes the wallet files created by
     * {@link #copyWalletTo(Path)} and removes the destination directory when it
     * is empty. Other files in a caller-provided destination are preserved.</p>
     */
    public static final class Wallet implements AutoCloseable {

        private final Path directory;
        private boolean closed;

        private Wallet(Path directory) {
            this.directory = directory;
        }

        /**
         * Returns the directory containing the copied wallet files.
         *
         * @return wallet directory
         */
        public Path getDirectory() {
            return directory;
        }

        @Override
        public void close() throws IOException {
            if (closed) {
                return;
            }

            IOException failure = null;
            for (String fileName : WALLET_FILES) {
                try {
                    Files.deleteIfExists(directory.resolve(fileName));
                } catch (IOException exception) {
                    failure = appendFailure(failure, exception);
                }
            }
            try {
                Files.deleteIfExists(directory);
            } catch (DirectoryNotEmptyException ignored) {
                // Preserve unrelated files in a caller-provided directory.
            } catch (IOException exception) {
                failure = appendFailure(failure, exception);
            }

            if (failure != null) {
                throw failure;
            }
            closed = true;
        }

        private static IOException appendFailure(IOException current, IOException next) {
            if (current == null) {
                return next;
            }
            current.addSuppressed(next);
            return current;
        }
    }

    @Override
    protected void configure() {
        requireConfigured(ADMIN_PASSWORD_ENV, "Call withAdminPassword(...) before starting the container");
        requireConfigured(WALLET_PASSWORD_ENV, "Call withWalletPassword(...) before starting the container");
        withEnv(WORKLOAD_TYPE_ENV, workloadType.name());
        if (databaseName != null) {
            withEnv(DATABASE_NAME_ENV, databaseName);
        }
    }

    static void configureRequiredRuntime(HostConfig hostConfig) {
        hostConfig.withCapAdd(Capability.SYS_ADMIN)
                .withDevices(new Device("rwm", FUSE_DEVICE, FUSE_DEVICE));
    }

    private void requireConfigured(String variable, String message) {
        if (getEnvMap().get(variable) == null) {
            throw new IllegalStateException(message);
        }
    }

    private void updateWalletNetworkAddresses(Path tnsNames) throws IOException {
        String updatedTnsNames = Files.readString(tnsNames)
                .replaceAll("(?i)(HOST\\s*=\\s*)localhost", "$1" + Matcher.quoteReplacement(getHost()))
                .replaceAll("(?i)(PORT\\s*=\\s*)1521", "$1" + getTlsPort())
                .replaceAll("(?i)(PORT\\s*=\\s*)1522", "$1" + getMtlsPort());
        Files.writeString(tnsNames, updatedTnsNames);
    }

    private void provisionAppUser(AppUserConfiguration configuration) {
        String scriptPath = APP_USER_SCRIPT_PREFIX + UUID.randomUUID() + ".sql";
        ContainerLaunchException failure = null;

        try {
            copyFileToContainer(
                    Transferable.of(createAppUserScript(configuration), OWNER_READ_WRITE_FILE_MODE), scriptPath);
            execInContainerOrThrow("ADB application-user provisioning failed", scriptPath);
        } catch (IOException exception) {
            failure = new ContainerLaunchException("Failed to run ADB application-user provisioning", exception);
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            failure = new ContainerLaunchException(
                    "Interrupted while provisioning the ADB application user", exception);
        } catch (ContainerLaunchException exception) {
            failure = exception;
        } catch (RuntimeException exception) {
            failure = new ContainerLaunchException("Failed to prepare ADB application-user provisioning", exception);
        }

        ContainerLaunchException cleanupFailure = removeAppUserScript(scriptPath);
        if (failure != null) {
            if (cleanupFailure != null) {
                failure.addSuppressed(cleanupFailure);
            }
            throw failure;
        }
        if (cleanupFailure != null) {
            throw cleanupFailure;
        }
    }

    private void execInContainerOrThrow(String failureMessage, String scriptPath)
            throws IOException, InterruptedException {
        Container.ExecResult result = execInContainer(ExecConfig.builder()
                .user(ROOT_USER)
                .envVars(Map.of("TNS_ADMIN", TLS_WALLET_PATH))
                .command(new String[] {"sqlplus", "-L", "-S", "/nolog", "@" + scriptPath})
                .build());
        if (result.getExitCode() != 0) {
            throw new ContainerLaunchException(failureMessage + " (exit code " + result.getExitCode() + ")");
        }
    }

    private ContainerLaunchException removeAppUserScript(String scriptPath) {
        try {
            execInContainer(ExecConfig.builder()
                    .user(ROOT_USER)
                    .command(new String[] {"rm", "-f", scriptPath})
                    .build());
            return null;
        } catch (IOException exception) {
            return new ContainerLaunchException("Failed to remove ADB application-user provisioning script", exception);
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            return new ContainerLaunchException(
                    "Interrupted while removing ADB application-user provisioning script", exception);
        } catch (RuntimeException exception) {
            return new ContainerLaunchException("Failed to remove ADB application-user provisioning script", exception);
        }
    }

    private String createAppUserScript(AppUserConfiguration configuration) {
        String adminPassword = getEnvMap().get(ADMIN_PASSWORD_ENV);
        requireValidSqlPassword(adminPassword, "Admin password");
        String escapedAppUserPassword = configuration.password().replace("'", "''");
        String roleGrant = appUserRoles.isEmpty()
                ? ""
                : "GRANT %s TO %s;%n".formatted(String.join(", ", appUserRoles), configuration.username());
        return """
                WHENEVER SQLERROR EXIT SQL.SQLCODE
                SET DEFINE OFF
                CONNECT %s/"%s"@%s
                DECLARE
                    USER_COUNT NUMBER;
                BEGIN
                    SELECT COUNT(*) INTO USER_COUNT FROM DBA_USERS WHERE USERNAME = '%s';
                    IF USER_COUNT = 0 THEN
                        EXECUTE IMMEDIATE 'CREATE USER %s IDENTIFIED BY "%s" QUOTA UNLIMITED ON DATA';
                    ELSE
                        EXECUTE IMMEDIATE 'ALTER USER %s IDENTIFIED BY "%s" ACCOUNT UNLOCK';
                    END IF;
                END;
                /
                ALTER USER %s QUOTA UNLIMITED ON DATA;
                GRANT CREATE SESSION TO %s;
                %s\
                EXIT;
                """.formatted(
                ORACLE_ADMIN_USERNAME,
                adminPassword,
                getMtlsServiceAlias(),
                configuration.username(),
                configuration.username(),
                escapedAppUserPassword,
                configuration.username(),
                escapedAppUserPassword,
                configuration.username(),
                configuration.username(),
                roleGrant);
    }

    private static String requireNonBlank(String value, String name) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(name + " cannot be null or blank");
        }
        return value;
    }

    private static String requireAppUserUsername(String username) {
        String normalizedUsername = requireUnquotedIdentifier(username, "Application user name");
        if (ORACLE_ADMIN_USERNAME.equals(normalizedUsername)
                || "SYS".equals(normalizedUsername)
                || "SYSTEM".equals(normalizedUsername)
                || "PDBADMIN".equals(normalizedUsername)) {
            throw new IllegalArgumentException("Application user name cannot be an administrator account");
        }
        return normalizedUsername;
    }

    private static String requireUnquotedIdentifier(String value, String name) {
        String normalizedValue = requireNonBlank(value, name).toUpperCase(Locale.ROOT);
        if (!normalizedValue.matches(ORACLE_IDENTIFIER_PATTERN)) {
            throw new IllegalArgumentException(name + " must be a valid unquoted Oracle AI Database identifier");
        }
        return normalizedValue;
    }

    private static void requireValidSqlPassword(String password, String name) {
        requireNonBlank(password, name);
        if (password.indexOf('"') >= 0 || password.indexOf('\n') >= 0 || password.indexOf('\r') >= 0) {
            throw new IllegalArgumentException(name + " cannot contain double quotes or line breaks");
        }
    }

    private static void requireValidAdminPassword(String password) {
        requireNonBlank(password, "Admin password");
        if (password.length() < 12 || password.length() > 30
                || password.equals(password.toLowerCase(Locale.ROOT))
                || password.equals(password.toUpperCase(Locale.ROOT))
                || password.chars().noneMatch(Character::isDigit)
                || password.toUpperCase(Locale.ROOT).contains("ADMIN")) {
            throw new IllegalArgumentException("Admin password must be 12-30 characters with uppercase, lowercase, and numeric characters, and cannot contain ADMIN");
        }
    }

    private static void requireValidWalletPassword(String password) {
        requireNonBlank(password, "Wallet password");
        boolean hasLetter = password.chars().anyMatch(Character::isLetter);
        boolean hasNumberOrSpecialCharacter = password.chars()
                .anyMatch(character -> Character.isDigit(character) || !Character.isLetterOrDigit(character));
        if (password.length() < 8 || !hasLetter || !hasNumberOrSpecialCharacter) {
                throw new IllegalArgumentException("Wallet password must have at least eight characters, including letters and numbers or special characters");
        }
    }

    private record AppUserConfiguration(String username, String password) {
    }
}
