spring:
  application:
    name: oracle-spring-boot-samples-wallet

  # Datasource Configuration
  datasource:
    url: jdbc:oracle:thin:@<TNSNAMES_ORA_ENTRY>?TNS_ADMIN=<DIRECTORY_OF_UNZIPPED_WALLET>
    username: ADMIN
    password: <PASSWORD>
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: UCPWalletConnectionPool
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30