== Basic Spring Web Application for Oracle Backend for Spring Boot and Microservices

This project contains a web service that can be deployed on link:https://bit.ly/OracleAI-microservices[Oracle Backend for Microservices and AI]
and includes configuration for the well-known endpoints provided by the platform.
The web service will accept HTTP GET requests at `http://localhost:8080/greeting`.

It will respond with a JSON representation of a greeting, as the following listing shows:

====
[source,json]
----
{"id":1,"content":"Hello, World!"}
----
====

You can customize the greeting with an optional `name` parameter in the query string, as
the following listing shows:

====
[source,text]
----
http://localhost:8080/greeting?name=User
----
====

The `name` parameter value overrides the default value of `World` and is reflected in the
response, as the following listing shows:

====
[source,json]
----
{"id":1,"content":"Hello, User!"}
----
====

=== Building and running locally

[source,bash]
----
./mvnw spring-boot:run -Dspring-boot.run.profiles=local ????
----

Then access the endpoint

[source,bash]
----
curl http://localhost:8080/greeting?name=User
----

== About the sample code

The link:./pom.xml[Maven POM file] contains dependencies for commonly used features.
You should review the POM file and remove any dependencies that you do not need.
Note that there may be dependency configuration in the link:./src/main/resources/application.yaml[Spring application configuration file]
as well, which you should remove if you remove the matching dependency.

The link:./src/main/resources/application.yaml[Spring application configuration file] contains
comments that explain what the various configuration included is for.
You can use this as an example starting point and modify it to suit your needs. 

There are example link:./src/main/resources/db/changelog[Liquibase] configuration files
provided.  If you want to use Liquibase, you will need to modify these to meet
your needs.  Note that the use of Liquibase is optional.  If you do not wish to 
use Liquibase you can safely remove the `src/main/resources/db` directory, the
Liquibase dependency in the POM, the Liquibase build plugin in the POM, and the
Liquibase configuration in the Spring application configuration file.

This example uses Oracle Universal Connection Pool (UCP) and also includes the
dependencies for Oracle Wallet authentication and mTLS.  These are optional. 
If you prefer to use HikariCP, you can remove the dependencies from the POM 
and the `oracleucp` section in the datasource configuration in the Spring
application configuration file.