// Copyright (c) 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

[#spring-cloud-oci-core]
== Spring Cloud OCI Core

Spring Cloud OCI provides a Spring Boot starter to auto-configure the core components.

Maven coordinates, using <<getting-started.adoc#bill-of-materials, Spring Cloud OCI BOM>>:

[source,xml]
----
<dependency>
    <groupId>com.oracle.cloud.spring</groupId>
    <artifactId>spring-cloud-oci-starter</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    implementation("com.oracle.cloud.spring:spring-cloud-oci-starter")
}
----

=== Authentication Configuration

Spring Cloud OCI allows you to authenticate with OCI with various following available options.

==== Config File Based Authentication

By default config file based authentication is enabled. There are below optional configuration to choose custom config profile name and config file name.

----
spring.cloud.oci.config.profile = DEFAULT
spring.cloud.oci.config.file = <FILE_PATH>
----

==== Simple Authentication

Set the config.type to `SIMPLE` and set related required properties as below. All the below properties are mandatory.

----
spring.cloud.oci.config.type = SIMPLE
spring.cloud.oci.config.userId = <USER_ID>
spring.cloud.oci.config.tenantId = <TENANT_ID>
spring.cloud.oci.config.fingerprint = <FINGERPRINT>
spring.cloud.oci.config.privateKey = <PRIVATE_KEY_FILE_PATH>
spring.cloud.oci.config.passPhrase = <PASS_PHRASE>
spring.cloud.oci.config.region = <REGION>
----
Note: spring.cloud.oci.config.passPhrase is optional

==== Instance Principal Configuration

Set the config.type to `INSTANCE_PRINCIPAL` as below.

----
spring.cloud.oci.config.type = INSTANCE_PRINCIPAL
----

==== Resource Principal Configuration

Set the config.type to `RESOURCE_PRINCIPAL` as below.

----
spring.cloud.oci.config.type = RESOURCE_PRINCIPAL
----

=== Region Configuration

OCI services are available in different regions. Based on the custom requirements, the user can host the application on different OCI regions. The below configuration allows to set specific region for the entire application.

----
spring.cloud.oci.region.static = us-ashburn-1
----

=== Compartment Configuration

A compartment is a logical container, to organize and control access to the Oracle Cloud Infrastructure (OCI) Resources (Compute, Storage, Network, Load Balancer, etc) created within that compartment. Below configuration allows you to set default compartment for your application.

----
spring.cloud.oci.compartment.static = <COMPARTMENT_OCID>
----
