// Copyright (c) 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

[#spring-cloud-oci-core]
== Spring Cloud OCI Core

Spring Cloud OCI provides a Spring Boot starter to auto-configure the core components.

Maven coordinates, using <<getting-started.adoc#bill-of-materials, Spring Cloud OCI BOM>>:

[source,xml]
----
<dependency>
    <groupId>com.oracle.cloud.spring</groupId>
    <artifactId>spring-cloud-oci-starter</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    implementation("com.oracle.cloud.spring:spring-cloud-oci-starter")
}
----

=== Authentication Configuration

Spring Cloud OCI allows you to authenticate with OCI with various following available options.

==== Config File Based Authentication

By default config file based authentication is enabled, to set it explicitly set the property spring.cloud.oci.config.type to `FILE`. There are below optional configuration to choose custom config profile name and config file name.

----
spring.cloud.oci.config.profile = DEFAULT
spring.cloud.oci.config.file = <FILE_PATH>
----

For further details about the Authentication config file refer https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm[SDK and CLI Configuration File]

==== Simple Authentication

Set the property spring.cloud.oci.config.type to `SIMPLE` and add below properties:

----
spring.cloud.oci.config.type = SIMPLE
spring.cloud.oci.config.userId = ocid1.user.oc1..<unique_ID>
spring.cloud.oci.config.tenantId = ocid1.tenancy.oc1..<unique_ID>
spring.cloud.oci.config.fingerprint = <FINGERPRINT>
spring.cloud.oci.config.privateKey = <PRIVATE_KEY_FILE_PATH>
spring.cloud.oci.config.passPhrase = <PASS_PHRASE>
spring.cloud.oci.config.region = <REGION>
----
Note: All the above properties are mandatory except spring.cloud.oci.config.passPhrase

==== Instance Principal Configuration

Set the config.type to `INSTANCE_PRINCIPAL` as below.

----
spring.cloud.oci.config.type = INSTANCE_PRINCIPAL
----
For further details refer https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/callingservicesfrominstances.htm[OCI Instance Principal Authentication]

==== Resource Principal Configuration

Set the config.type to `RESOURCE_PRINCIPAL` as below.

----
spring.cloud.oci.config.type = RESOURCE_PRINCIPAL
----

For further details refer https://docs.public.oneportal.content.oci.oraclecloud.com/en-us/iaas/Content/API/Concepts/sdk_authentication_methods.htm#sdk_authentication_methods_resource_principal[OCI Resource Principal Authentication]

=== Region Configuration

OCI services are available in different regions. Based on the custom requirements, the user can host the application on different OCI regions. The below configuration allows to set specific region for the entire application.

----
spring.cloud.oci.region.static = us-ashburn-1
----

Region value set in the above property takes precedence over the property `spring.cloud.oci.config.region` and `region` from the Authentication config file

=== Compartment Configuration

A compartment is a logical container, to organize and control access to the Oracle Cloud Infrastructure (OCI) Resources (Compute, Storage, Network, Load Balancer, etc) created within that compartment. Below configuration allows you to set default compartment for your application.

----
spring.cloud.oci.compartment.static = <COMPARTMENT_OCID>
----
