// Copyright (c) 2023, 2024, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

[#spring-cloud-oci-core]
== Spring Cloud Oracle Core

Spring Cloud Oracle provides a Spring Boot starter to auto-configure the core components.

Maven coordinates:

[source,xml]
----
<dependency>
    <groupId>com.oracle.cloud.spring</groupId>
    <artifactId>spring-cloud-oci-starter</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    implementation("com.oracle.cloud.spring:spring-cloud-oci-starter")
}
----

=== Authentication Configuration

Spring Cloud Oracle allows you to authenticate with OCI using various available options.

==== Configuration File Based Authentication

By default, configuration file based authentication is enabled. To set it explicitly, set the property `spring.cloud.oci.config.type` to `FILE`. The following are optional configurations to set a custom configuration profile name and file name.

----
spring.cloud.oci.config.profile = DEFAULT
spring.cloud.oci.config.file = <FILE_PATH>
----

For further details about the Authentication configuration file, refer https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm[SDK and CLI Configuration File]

==== Simple Authentication

Set the property `spring.cloud.oci.config.type` to `SIMPLE` and add the following properties:

----
spring.cloud.oci.config.type = SIMPLE
spring.cloud.oci.config.userId = ocid1.user.oc1..<unique_ID>
spring.cloud.oci.config.tenantId = ocid1.tenancy.oc1..<unique_ID>
spring.cloud.oci.config.fingerprint = <FINGERPRINT>
spring.cloud.oci.config.privateKey = <PRIVATE_KEY_FILE_PATH>
spring.cloud.oci.config.passPhrase = <PASS_PHRASE>
spring.cloud.oci.config.region = <REGION>
----
Note: All the preceding properties are mandatory except `spring.cloud.oci.config.passPhrase`

==== Instance Principal Configuration

Set the config.type to `INSTANCE_PRINCIPAL` as shown here.

----
spring.cloud.oci.config.type = INSTANCE_PRINCIPAL
----
For further details, refer to https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/callingservicesfrominstances.htm[OCI Instance Principal Authentication]

==== Resource Principal Configuration

Set the config.type to `RESOURCE_PRINCIPAL` as shown here.

----
spring.cloud.oci.config.type = RESOURCE_PRINCIPAL
----

For further details, refer to https://docs.public.oneportal.content.oci.oraclecloud.com/en-us/iaas/Content/API/Concepts/sdk_authentication_methods.htm#sdk_authentication_methods_resource_principal[OCI Resource Principal Authentication]

==== Session token Configuration

Set the config.type to `SESSION_TOKEN` as shown here.

----
spring.cloud.oci.config.type = SESSION_TOKEN
----

==== Workload Identity Configuration

Set the config.type to `WORKLOAD_IDENTITY` as shown here.

----
spring.cloud.oci.config.type = WORKLOAD_IDENTITY
----

For further details, refer to https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contenggrantingworkloadaccesstoresources.htm[OKE Workload Identity Authentication]

For further details, refer to https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdk_authentication_methods.htm#ariaid-title12

=== Region Configuration

OCI services are available in different regions. Based on the custom requirements, you can host the application on different OCI regions. The following configuration allows you to set a specific region for the entire application.

----
spring.cloud.oci.region.static = us-ashburn-1
----

Region value set in the preceding property takes precedence over the property `spring.cloud.oci.config.region` and `region` from the Authentication configuration file

=== Compartment Configuration

A compartment is a logical container, used to organize and control access to the OCI Resources (Compute, Storage, Network, Load Balancer, etc.) created within that compartment. The following configuration allows you to set the default compartment for your application.

----
spring.cloud.oci.compartment.static = <COMPARTMENT_OCID>
----
