// Copyright (c) 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

== Getting Started

This section describes how to get up to speed with Spring Cloud OCI libraries.

=== Spring Cloud OCI maven dependency management

Spring Cloud OCI module dependencies can be used directly in Maven with a direct configuration of the particular module. The Spring Cloud OCI module includes all transitive dependencies for the Spring modules and also the OCI SDK that are needed to operate the modules. The general dependency configuration will look like this:

----
<dependencies>
  <dependency>
    <groupId>com.oracle.cloud.spring</groupId>
    <artifactId>spring-cloud-oci-starter</artifactId>
    <version>{spring-cloud-oci-version}</version>
  </dependency>
</dependencies>
----

Different modules can be included by replacing the module name with the respective one (e.g. `spring-cloud-oci-starter-storage` instead of `spring-cloud-oci-starter`)

==== Starter Dependencies

Spring Cloud OCI offers https://github.com/oracle/spring-cloud-oci/tree/main/spring-cloud-oci-starters[starter dependencies] through Maven to easily depend on different modules of the library.
Each starter contains all the dependencies and transitive dependencies needed to begin using their corresponding Spring Cloud OCI module.

For example, if you wish to write a Spring application with Cloud Storage, you would include the `spring-cloud-oci-starter-storage` dependency in your project.
You do *not* need to include the underlying `spring-cloud-oci-storage` dependency, because the `starter` dependency includes it.

A summary of these artifacts are provided below.

|===
| Spring Cloud OCI Starter | Description | Maven Artifact Name

| Core
| Automatically configure authentication
| <<core.adoc#spring-cloud-oci-core, com.oracle.cloud.spring:spring-cloud-oci-starter>>

| Object Storage
| Provides integrations with OCI Cloud Storage
| <<storage.adoc#spring-cloud-storage, com.oracle.cloud.spring:spring-cloud-oci-starter-storage>>

|===

==== Spring Initializr

https://start.spring.io/[Spring Initializr] is a tool which generates the scaffolding code for a new Spring Boot project.
It handles the work of generating the Maven or Gradle build file so you do not have to manually add the dependencies yourself.

Spring Initializr offers below modules from Spring Cloud OCI that you can use to generate your project.

- *OCI Support*: The OCI Support module contains auto-configuration support for every Spring Cloud OCI integration.
Most of the autoconfiguration code is only enabled if the required dependency is added to your project.
- *OCI Storage*: OCI Storage integrations work out of the box.

=== Learning Spring Cloud OCI

There are a variety of resources to help you learn how to use Spring Cloud OCI libraries.

==== Sample Applications

The easiest way to learn how to use Spring Cloud OCI is to consult the https://github.com/oracle/spring-cloud-oci/tree/main/spring-cloud-oci-samples[sample applications on Github].
Spring Cloud OCI provides sample applications which demonstrate how to use every integration in the library.
The table below highlights several samples of the most commonly used integrations in Spring Cloud OCI.

|===
| OCI Integration | Sample Application

| Cloud Storage
| https://github.com/oracle-sample/spring-cloud-oci/tree/main/spring-cloud-oci-samples/spring-cloud-oci-storage-sample[spring-cloud-oci-storage-sample]

|===

Each sample application demonstrates how to use Spring Cloud OCI libraries in context and how to setup the dependencies for the project.
The applications are fully functional and can be deployed to OCI as well.

