// Copyright (c) 2023, 2024, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

[[spring-cloud-oci-reference]]
= Spring Cloud OCI

include::_attributes.adoc[]

Documentation for version *{project-version}*

== Introduction

Spring Cloud for OCI, part of the Spring Cloud umbrella project, eases the integration with hosted OCI Services. It offers a convenient way to interact with OCI provided services using well-known Spring idioms and APIs, such as storage resources. Developers can build their application around the hosted services without having to worry about infrastructure or maintenance.

include::getting-started.adoc[]

include::core.adoc[]

include::storage.adoc[]

include::notifications.adoc[]

include::genai.adoc[]

include::logging.adoc[]

include::function.adoc[]

include::streaming.adoc[]

include::queues.adoc[]

include::adb.adoc[]

include::vault.adoc[]

include::ucp.adoc[]

include::aqjms.adoc[]

== Configuration properties

To see the list of all OCI-related configuration properties see the link:appendix.html[Appendix page].

=== Configuration Refresh

The following properties are supported for Configuration auto-refresh at runtime without the need to restart applications

|===
^|Name ^| Default

|spring.cloud.oci.config.profile | `DEFAULT`
|spring.cloud.oci.config.file | NA
|spring.cloud.oci.config.type | NA
|spring.cloud.oci.config.userId | NA
|spring.cloud.oci.config.tenantId | NA
|spring.cloud.oci.config.fingerprint | NA
|spring.cloud.oci.config.privateKey | NA
|spring.cloud.oci.config.passPhrase | NA
|spring.cloud.oci.config.region | NA
|spring.cloud.oci.region.static | NA
|spring.cloud.oci.compartment.static | NA
|spring.cloud.oci.logging.logId | NA

|===

Spring Boot Actuator can be used to explicitly refresh the externalized configuration during runtime. Add the corresponding build dependency to enable the Actuator:

Maven:
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
----

Gradle:
----
dependencies {
    implementation("org.springframework.boot:spring-boot-starter-actuator")
}
----

Set `management.endpoints.web.exposure.include=refresh` in the externalized configuration file of the Spring Boot Application to enable /actuator/refresh endpoint.

To refresh the updated Configuration properties at runtime make a POST API call to /actuator/refresh endpoint
