// Copyright (c) 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

[[spring-cloud-oci-reference]]
= Spring Cloud OCI

include::_attributes.adoc[]

*{project-version}*

== Introduction

Spring Cloud for OCI, part of the Spring Cloud umbrella project, eases the integration with hosted OCI Services. It offers a convenient way to interact with OCI provided services using well-known Spring idioms and APIs, such as storage resources. Developers can build their application around the hosted services without having to care about infrastructure or maintenance.

Spring Cloud OCI lets you leverage the power and simplicity of the Spring Framework to:

- Read and write from Spring Resources backed up by Oracle Cloud Storage

include::getting-started.adoc[]

include::core.adoc[]

include::storage.adoc[]

include::notifications.adoc[]

include::logging.adoc[]

== Configuration properties

To see the list of all OCI related configuration properties please check link:appendix.html[the Appendix page].

=== Configuration Refresh

The following properties are supported for Configuration auto-refresh at runtime without the need to restart applications

|===
|Name | Default

|spring.cloud.oci.config.profile | `DEFAULT`
|spring.cloud.oci.config.file |
|spring.cloud.oci.config.type |
|spring.cloud.oci.config.userId |
|spring.cloud.oci.config.tenantId |
|spring.cloud.oci.config.fingerprint |
|spring.cloud.oci.config.privateKey |
|spring.cloud.oci.config.passPhrase |
|spring.cloud.oci.config.region |
|spring.cloud.oci.region.static |
|spring.cloud.oci.compartment.static |
|spring.cloud.oci.logging.logId |

|===

Spring Boot Actuator can be used to explicitly refresh the externalized configuration during runtime. Add the corresponding build dependency to enable the Actuator:

Maven:
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
----

Gradle:
----
dependencies {
    implementation("org.springframework.boot:spring-boot-starter-actuator")
}
----

Set `management.endpoints.web.exposure.include=refresh` in the externalized configuration file of the Spring Boot Application to enable /actuator/refresh endpoint.

To refresh the updated Configuration properties at runtime make a POST API call to /actuator/refresh endpoint
