// Copyright (c) 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

[#cloud-logging]
== Cloud Logging

https://docs.oracle.com/en-us/iaas/Content/Logging/home.htm/[Oracle Cloud Infrastructure (OCI) Logging] service is a highly scalable and fully managed single pane of glass for all the logs in your tenancy. Logging provides access to logs from Oracle Cloud Infrastructure resources. These logs include critical diagnostic information that describes how resources are performing and being accessed. Use Logging to enable, manage, and search Audit, Service and Custom logs. The Spring Cloud module for OCI Logging allows ingesting logs associated with a logId.
A Spring Boot starter is provided to auto-configure the Logging component.

Maven coordinates, using <<getting-started.adoc#bill-of-materials, Spring Cloud OCI BOM>>:

[source,xml]
----
<dependency>
    <groupId>com.oracle.cloud.spring</groupId>
    <artifactId>spring-cloud-oci-starter-logging</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    implementation("com.oracle.cloud.spring:spring-cloud-oci-starter-logging")
}
----

This starter is also available from https://start.spring.io/[Spring Initializr] through the `OCI Logging` entry.

=== Using Cloud Logging

The starter automatically configures and registers a `Logging` bean in the Spring application context.
The `Logging` bean (link[Javadoc]) can be used to ingest logs associated with a logId.

[source,java]
----
@Autowired
private Logging logging;

public void putLogs() {

    PutLogsResponse response = logging.putLogs("log-text");
}
----


=== Configuration

The Spring Boot Starter for Oracle Cloud Logging provides the following configuration options:

|===
| Name | Description | Required | Default value
| `spring.cloud.oci.logging.enabled` | Enables the OCI Logging APIs. | No | `true`
|===


=== Sample

A https://github.com/oracle/spring-cloud-oci/tree/main/spring-cloud-oci-samples/spring-cloud-oci-logging-sample[sample application] is available.
