// Copyright (c) 2023, 2024, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

[#cloud-notifications]
== Cloud Notifications

https://www.oracle.com/in/devops/notifications/[OCI Notifications] is a highly available, low latency publish/subscribe (pub/sub) service that sends alerts and messages to Oracle Cloud Functions, email, SMS, and message delivery partners, including Slack, PagerDuty and custom HTTPS endpoint. Spring Cloud module for Oracle Cloud Notifications allows you to create a Topic, then create and publish messages to multiple subscription types such as Oracle Cloud Functions, email, SMS, Slack, PagerDuty and custom HTTPS endpoint.
A Spring Boot starter is provided to autoconfigure the various Notification components.

Maven coordinates:

[source,xml]
----
<dependency>
    <groupId>com.oracle.cloud.spring</groupId>
    <artifactId>spring-cloud-oci-starter-notification</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    implementation("com.oracle.cloud.spring:spring-cloud-oci-starter-notification")
}
----

=== Using Cloud Notifications

The starter automatically configures and registers a `Notification` bean in the Spring application context.
The `Notification` bean (https://oracle.github.io/spring-cloud-oci/{project-version}/javadocs/com/oracle/cloud/spring/notification/package-summary.html[Javadoc]) can be used to create a Topic, create, list, get a Subscription, and publish messages to the Subscriptions in a Topic.

[source,java]
----
@Autowired
private Notification notification;

public void createTopic() {

    CreateTopicResponse response = notification.createTopic("my-topic", <<compartment-ocid>>);
}
----


=== Configuration

The Spring Boot Starter for Oracle Cloud Notifications provides the following configuration options:

|===
^| Name ^| Description ^| Required ^| Default value
| `spring.cloud.oci.notification.enabled` | Enables the OCI Notifications APIs. | No | `true`
|===


=== Sample

A sample application provided https://github.com/oracle/spring-cloud-oci/tree/main/spring-cloud-oci-samples/spring-cloud-oci-notification-sample[here] contains the examples to demonstrates the usage of OCI Spring Cloud Notification module.
