// Copyright (c) 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

[#cloud-notifications]
== Cloud Notifications

https://www.oracle.com/in/devops/notifications/[Oracle Cloud Infrastructure (OCI) Notifications] is a highly available, low-latency publish/subscribe (pub/sub) service that sends alerts and messages to Oracle Cloud Functions, email, SMS, and message delivery partners, including Slack, PagerDuty and custom HTTPS endpoint. Spring Cloud module for Oracle Cloud Notifications allows to create a Topic and create and publish messages to multiple subsctiption types like Oracle Cloud Functions, email, SMS, Slack, PagerDuty and custom HTTPS endpoint.
A Spring Boot starter is provided to auto-configure the various Notification components.

Maven coordinates, using <<getting-started.adoc#bill-of-materials, Spring Cloud OCI BOM>>:

[source,xml]
----
<dependency>
    <groupId>com.oracle.cloud.spring</groupId>
    <artifactId>spring-cloud-oci-starter-notification</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    implementation("com.oracle.cloud.spring:spring-cloud-oci-starter-notification")
}
----

This starter is also available from https://start.spring.io/[Spring Initializr] through the `OCI Notifications` entry.

=== Using Cloud Notifications

The starter automatically configures and registers a `Notification` bean in the Spring application context.
The `Notification` bean (link[Javadoc]) can be used to create Topic, create/list/get Subscription and publish message to the Subscriptions in a Topic.

[source,java]
----
@Autowired
private Notification notification;

public void createTopic() {

    CreateTopicResponse response = notification.createTopic("my-topic", <<compartment-ocid>>);
}
----


=== Configuration

The Spring Boot Starter for Oracle Cloud Notifications provides the following configuration options:

|===
| Name | Description | Required | Default value
| `spring.cloud.oci.notification.enabled` | Enables the OCI Notifications APIs. | No | `true`
|===


=== Sample

A https://github.com/oracle/spring-cloud-oci/tree/main/spring-cloud-oci-samples/spring-cloud-oci-notification-sample[sample application] is available.
