// Copyright (c) 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

[#cloud-storage]
== Cloud Storage

https://www.oracle.com/in/cloud/storage/[Oracle Cloud Storage] allows you to store any types of file.
A Spring Boot starter is provided to auto-configure the various Storage components.

Maven coordinates, using <<getting-started.adoc#bill-of-materials, Spring Cloud OCI BOM>>:

[source,xml]
----
<dependency>
    <groupId>com.oracle.cloud.spring</groupId>
    <artifactId>spring-cloud-oci-starter-storage</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    implementation("com.oracle.cloud.spring:spring-cloud-oci-starter-storage")
}
----

=== Using Cloud Storage

The starter automatically configures and registers a `Storage` bean in the Spring application context.
The `Storage` bean (link[Javadoc]) can be used to list, create, update or delete buckets and objects.

[source,java]
----
@Autowired
private Storage storage;

public void createBucketAndUploadFile() {
    Bucket bucket = storage.createBucket("my-bucket");

    storage.upload("my-bucket", "my-file.txt", inputStream, StorageObjectMetadata.builder().contentType("text/plain").build());
}
----

=== Cloud Storage Objects Spring Resources

https://docs.spring.io/spring/docs/current/spring-framework-reference/html/resources.html[Spring Resources] are an abstraction for several low-level resources, such as file system files, classpath files, servlet context-relative files, etc.
Spring Cloud OCI adds a new resource type for Oracle Cloud Object Storage.

The Spring Resource Abstraction for Oracle Cloud Storage allows Object Storage objects to be accessed by their URL using the `@Value` annotation or the Spring application context:

[source,java]
----
@Value("https://objectstorage.us-chicago-1.oraclecloud.com/n/${OCI_NAMESPACE}/b/${OCI_BUCKET}/o/${OCI_OBJECT}")
private Resource myObjectResource;
----

[source,java]
----
SpringApplication.run(...).getResource("Object Storage URL");
----

This creates a `Resource` object that can be used to read the object, among https://docs.spring.io/spring/docs/current/spring-framework-reference/html/resources.html#resources-resource[other possible operations].

Currently this resource is only readable.

=== Configuration

The Spring Boot Starter for Oracle Cloud Storage provides the following configuration options:

|===
^| Name ^| Description ^| Required ^| Default value
| `spring.cloud.oci.storage.enabled` | Enables the OCI storage APIs. | No | `true`
|===


=== Sample

A sample application provided https://github.com/oracle/spring-cloud-oci/tree/main/spring-cloud-oci-samples/spring-cloud-oci-storage-sample[here] contains the examples to demonstrate the usage of OCI Spring Cloud Storage module.
