// Copyright (c) 2023, 2024, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

[#cloud-stream]
== Cloud Stream

https://docs.oracle.com/en-us/iaas/Content/Streaming/home.htm[OCI Streaming] service provides a fully managed, scalable, and durable solution for ingesting and consuming high-volume data streams in real time.
A Spring Boot starter is provided to autoconfigure the Streaming component.

Maven coordinates::

[source,xml]
----
<dependency>
    <groupId>com.oracle.cloud.spring</groupId>
    <artifactId>spring-cloud-oci-starter-streaming</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    implementation("com.oracle.cloud.spring:spring-cloud-oci-starter-streaming")
}
----

=== Using Cloud Streaming

The starter automatically configures and registers a `Streaming` bean in the Spring application context.
The `Streaming` bean (https://oracle.github.io/spring-cloud-oci/1.1.0/javadocs/com/oracle/cloud/spring/streaming/package-summary.html[Javadoc]) can be used to create streamPool, stream in OCI and ingest and consume high-volume data streams with a streamId

[source,java]
----
@Autowired
private Streaming streaming;

public void putMessages() {

    PutMessagesResponse response = streaming.putMessages(streamId, "key".getBytes(), "value"..getBytes());
}

public void getMessages() {

    GetMessagesResponse response = streaming.getMessages(streamId, "cursor");
}
----


=== Configuration

The Spring Boot Starter for Oracle Cloud Stream provides the following configuration options:

|===
^| Name ^| Description ^| Required ^| Default value
| `spring.cloud.oci.stream.enabled` | Enables the OCI Streaming APIs. | No | `true`
|===


=== Sample

A sample application provided https://github.com/oracle/spring-cloud-oci/tree/main/spring-cloud-oci-samples/spring-cloud-oci-streaming-sample[here] contains the examples to demonstrates the usage of OCI Spring Cloud Streaming module.
