// Copyright (c) 2026, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
package com.oracle.spring.spatial;

import org.springframework.util.Assert;

/**
 * Represents a GeoJSON value and SRID that can be bound into Oracle Spatial
 * SQL generated by {@link OracleSpatialJdbcOperations}.
 */
public final class SpatialGeometry {
    private final String bindName;
    private final String geoJson;
    private final int srid;

    SpatialGeometry(String bindName, String geoJson, int srid) {
        Assert.hasText(bindName, "bindName must not be blank");
        Assert.hasText(geoJson, "geoJson must not be blank");
        Assert.isTrue(srid > 0, "srid must be greater than 0");
        this.bindName = bindName;
        this.geoJson = geoJson;
        this.srid = srid;
    }

    String bindName() {
        return bindName;
    }

    /**
     * Returns the original GeoJSON payload.
     *
     * @return GeoJSON value
     */
    public String geoJson() {
        return geoJson;
    }

    /**
     * Returns the SRID associated with this geometry.
     *
     * @return Oracle Spatial SRID
     */
    public int srid() {
        return srid;
    }
}
