services:
  grafana-lgtm:
    container_name: lgtm
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000' # UI
      - '4317:4317'
      - '4318:4318'
  free23ai:
    image: gvenzl/oracle-free:23.26.1-slim-faststart
    container_name: free23ai
    ports:
      - 1522:1521
    environment:
      - ORACLE_PASSWORD=Welcome12345
    volumes:
      - ./oracle:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "lsnrctl status | grep READY"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s