// Copyright (c) 2023, 2024, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

[#cloud-function]
== Cloud Functions

https://docs.oracle.com/en-us/iaas/Content/Functions/Concepts/functionsoverview.htm[OCI Functions] is a fully managed, multi-tenant, highly scalable, on-demand, Functions-as-a-Service platform. It is built on enterprise-grade Oracle Cloud Infrastructure and powered by the Fn Project open source engine. Use OCI Functions when you want to focus on writing code to meet business needs. The Spring Cloud Oracle module for OCI Functions allows to invoke an OCI Function.
A Spring Boot starter is provided to autoconfigure the Function component.

Maven coordinates:

[source,xml]
----
<dependency>
    <groupId>com.oracle.cloud.spring</groupId>
    <artifactId>spring-cloud-oci-starter-function</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    implementation("com.oracle.cloud.spring:spring-cloud-oci-starter-function")
}
----

=== Using Cloud Functions

The starter automatically configures and registers a `Function` bean in the Spring application context.
The `Function` bean (https://oracle.github.io/spring-cloud-oci/{project-version}/javadocs/com/oracle/cloud/spring/function/package-summary.html[Javadoc]) can be used to invoke a function with parameter inputs 'functionOcid' and 'endpoint'

[source,java]
----
@Autowired
private Function function;

public void invoke() {

    InvokeFunctionResponse invokeFunctionResponse = function.invokeFunction(functionOcid, endpoint, mode, requestBody);
}
----


=== Configuration

The Spring Boot Starter for Oracle Cloud Function provides the following configuration options:

|===
^| Name ^| Description ^| Required ^| Default value
| `spring.cloud.oci.function.enabled` | Enables the OCI Functions APIs. | No | `true`
|===


=== Sample

A sample application provided https://github.com/oracle/spring-cloud-oracle/tree/main/spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-function-sample[here] contains the examples to demonstrates the usage of OCI Spring Cloud Function module.
