// Copyright (c) 2023, 2024, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

== Getting Started

This section describes how to get started using Spring Cloud Oracle libraries.

=== Spring Cloud Oracle

Spring Cloud Oracle module dependencies can be used directly in Maven with a direct configuration of the module. The Spring Cloud Oracle module includes all transitive dependencies for the Spring modules, and the OCI SDK that are needed to operate the modules. The general dependency configuration will look like this:

----
<dependencies>
  <dependency>
    <groupId>com.oracle.cloud.spring</groupId>
    <artifactId>spring-cloud-oci-starter</artifactId>
    <version>{spring-cloud-oci-version}</version>
  </dependency>
</dependencies>
----

Different modules can be included by replacing the module name with the respective one (for example, `spring-cloud-oci-starter-storage` instead of `spring-cloud-oci-starter`)

==== Starter Dependencies

Spring Cloud Oracle offers https://github.com/oracle/spring-cloud-oci/tree/main/spring-cloud-oci-starters[starter dependencies] through Maven to easily depend on different modules of the library.
Each starter contains all the dependencies and transitive dependencies needed to begin using their corresponding Spring Cloud Oracle module.

For example, to write a Spring application with Cloud Storage, you include the `spring-cloud-oci-starter-storage` dependency in your project.
You do *not* need to include the underlying `spring-cloud-oci-storage` dependency, because the `starter` dependency includes it.

A summary of these artifacts is provided here.

|===
^| Spring Cloud Oracle Starter ^| Description ^| Maven Artifact Name

| Core
| Automatically configure authentication
| <<core.adoc#spring-cloud-oci-core, com.oracle.cloud.spring:spring-cloud-oci-starter>>

| Object Storage
| Provides integrations with OCI Cloud Storage
| <<storage.adoc#spring-cloud-storage, com.oracle.cloud.spring:spring-cloud-oci-starter-storage>>

|===


=== Learning Spring Cloud Oracle

There are a variety of resources to help you learn how to use Spring Cloud Oracle libraries.

==== Sample Applications

The easiest way to learn how to use Spring Cloud Oracle is to consult the https://github.com/oracle/spring-cloud-oracle/tree/main/spring-cloud-oci/spring-cloud-oci-samples[sample applications on Github].
Spring Cloud Oracle provides sample applications which demonstrate how to use every integration in the library.
The following table highlights several samples of the most used integrations in Spring Cloud Oracle.

|===
^| OCI Integration ^| Sample Application

| Cloud Storage
| https://github.com/oracle/spring-cloud-oracle/tree/main/spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-storage-sample[spring-cloud-oci-storage-sample]

| Cloud Notification
| https://github.com/oracle/spring-cloud-oracle/tree/main/spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-notification-sample[spring-cloud-oci-notification-sample]

| Cloud Generative AI
| https://github.com/oracle/spring-cloud-oracle/tree/main/spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample[spring-cloud-oci-gen-ai-sample]

| Cloud Logging
| https://github.com/oracle/spring-cloud-oracle/tree/main/spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-logging-sample[spring-cloud-oci-logging-sample]

| Cloud Streaming
| https://github.com/oracle/spring-cloud-oracle/tree/main/spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-streaming-sample[spring-cloud-oci-streaming-sample]

| Cloud Function
| https://github.com/oracle/spring-cloud-oracle/tree/main/spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-function-sample[spring-cloud-oci-function-sample]

| Cloud Queue
| https://github.com/oracle/spring-cloud-oracle/tree/main/spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-queue-sample[spring-cloud-oci-queue-sample]

| Oracle Autonomous Database
| https://github.com/oracle/spring-cloud-oracle/tree/main/spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-adb-samples[spring-cloud-oci-adb-samples]

| Generative AI
| https://github.com/oracle/spring-cloud-oracle/tree/main/spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample[spring-cloud-oci-gen-ai-sample]

| Vault
| https://github.com/oracle/spring-cloud-oracle/tree/main/spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-vault-sample[spring-cloud-oci-vault-sample]

|===

Each sample application demonstrates how to use Spring Cloud Oracle libraries in context and how to setup the dependencies for the project.
The applications are fully functional and can be deployed to OCI as well.

