-- Copyright (c) 2026, Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

CREATE TABLE students (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE
);

INSERT INTO students (first_name, email)
VALUES ('Alice', 'alice.smith@example.edu');

COMMIT;
